version: '3.8'

services:
    app:
        container_name: holo-mentor-app
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
        env_file: .env
        command: yarn dev
